### ISSUE TITLE
Is there a way to have the go build system make the syso files?

### ISSUE THREAD

**Issue by blacktop** [jpap/go-zydis#2]
Is there a way to have the go build system make the syso files, instead of using the git lfs included ones?  

I know this would slow down building a lot on the Go side, but would be nice for the paranoid people out there 😏 

My binja arm64 [bindings](https://github.com/blacktop/arm64-cgo) don't include any pre-compiled files, but I know that the zydis builder is MUCH more complex and uses cmake etc

**Comment by jpap** [comment]
As you point out, zydis uses a nontrivial build system.  Nevertheless you can absolutely avoid the prebuilt syso files by:
* Doing some research by building zydis for each platform/arch, and note down the differences to each source/header file, if any, in each case.
* Copy all of the zydis source files into the Go package, and for each variation above, break it out into a separate file named `$NAME_$GOOS_$GOARCH.[ch]` so the go build tool selectively compiles the variation for a given GOOS/GOARCH pair.
* Make sure any CFLAGS and LDFLAGS that are needed to build the zydis library are specified in the Go source file(s) that use cgo, because that's where the go build tool gets its flags from otherwise.

The above is a lot of work: both up-front and each time a maintainer wants to update the zydis library.  It also "pollutes" the package directory with a lot of C files that distracts from the Go wrappers and adds friction to developing the Go package.

The paranoid are better off vendoring this package, and rebuilding the syso files from scratch.  The burden of repeating that process is of course on them each time they want an upgrade... That process can be automated with a script in a similar way as I have done for rebuilding the syso files in this project.

A separate path is to rely on dynamic linking, and the user having zydis installed on their system: that would involve removing the syso files from the project, and updating the #cgo directives to enable the dynamic link.  I ruled this out at the beginning because I wanted a statically linked binary at the end of the day.

While you could support both static and dynamic linking through the use of build tags, it is cumbersome to implement as you'd need to move the syso files into an internal subpackage to "hide" it from the linker under dynamic link, and the end-user has a poorer experience because the burden is now on them to have the zydis shared library installed.

For a more general way to integrate the Go build tool with external build systems, you're better off proposing something with the Go team.  Feel free to cite this issue if you go down that path.  

There's also the bazel build system, but I've had no experience with it, and don't know if that could help you.  Please report back if it does!

For all of the above reasons, I'm unwilling to spend the time and maintenance burden moving away from the prebuilt syso files.  Please reopen this issue if you find a great way to drop the syso files without the drawbacks.
